# Generated by Django 3.2.11 on 2022-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamshut', '0002_auto_20220401_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='regis',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
